backend:
  name: github
  branch: main
  repo: Winterstellar-Studios/winterstellar-studios-site
  auth_endpoint: /api/auth
  base_url: https://winterstellarstudios.com
media_folder: "src/static/img"
public_folder: "/static/img"
media_library:
  name: cloudinary
  config:
    cloud_name: aidanjones
    api_key: 447781644958767
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Work"
    name: "work"
    folder: "src/work"
    create: true
    editor:
      preview: true
    fields:
      - label: "ID"
        name: "id"
        widget: "uuid"
      - widget: "string"
        label: "Title"
        name: "title"
      - widget: "text"
        label: "Description"
        name: "description"
        hint: "Displayed in search engine results"
        pattern: ['^.{0,120}$', "Maximum 120 characters"]
      - widget: "list"
        label: "Blocks"
        name: "blocks"
        required: false
        allow_add: true
        types:
          - label: "Image grid"
            name: "image_grid"
            widget: 'object'
            required: false
            fields:
              - widget: "list"
                label: "Grid"
                name: "grid"
                allow_add: true
                summary: "Grid item"
                label_singular: "grid item"
                required: false
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    choose_url: true
                  - label: 'URL'
                    name: 'url'
                    widget: 'list'
                    hint: "If the link you desire is a page on this site, choose one of the available collections and then one of the pages from the collection."
                    required: false
                    types:
                      - label: "Work"
                        name: work
                        widget: object
                        required: false
                        fields:
                        - label: 'Page'
                          name: 'page'
                          required: false
                          widget: relation
                          collection: "work"
                          search_fields: ["title"]
                          value_field: "id"
                      - label: "People"
                        name: people
                        widget: object
                        required: false
                        fields:
                        - label: 'Page'
                          name: 'page'
                          widget: relation
                          collection: "people"
                          search_fields: ["name"]
                          value_field: "id"
                          display_fields: ["name"]
                      - label: "Pages"
                        name: pages
                        widget: object
                        required: false
                        fields:
                        - label: "Page"
                          name: "page"
                          widget: "relation"
                          collection: "pages"
                          search_fields: ["title"]
                          value_field: "id"
                      - label: "External"
                        name: external
                        widget: object
                        required: false
                        fields:
                        - label: "URL"
                          name: url
                          widget: "string"
                          default: "https://www.example.com"
                          pattern: 
                            - '^(https?:\/\/|\/)\w+\.[^\s]+$|^\/[^\s]*$'
                            - "Text must be a valid URL."
          - widget: "object"
            label: "Media and text"
            name: "media_and_text"
            required: false
            fields:
              - label: "Display which first?"
                name: "order"
                widget: "select"
                options:
                  - label: "Media"
                    value: "media"
                  - label: "Text"
                    value: "text"
              - widget: "object"
                label: "Media"
                name: "media"
                required: false
                fields:
                - label: "Media"
                  name: "media"
                  widget: image
                  required: false
                - label: "Width"
                  name: "width"
                  widget: "object"
                  required: false
                  fields:
                    - label: "Display at original width?"
                      name: "original_width"
                      widget: "boolean"
                      required: false
                    - label: "Width"
                      info: "Number is in the percentage of the container that the media's width will occupy"
                      name: "width"
                      widget: "number"
                      value_type: "int"
                      min: 1
                      max: 100
                      step: 1
                      default: 50
                      required: false
              - label: "Text"
                name: "text"
                widget: "object"
                required: false
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "markdown"
                    required: false
                  - label: "Width"
                    info: "Number is in the percentage of the container that the image's width will occupy"
                    name: "width"
                    widget: "number"
                    value_type: "int"
                    min: 1
                    max: 100
                    step: 1
                    default: 50
                    required: false
                  - label: "Text Content"
                    name: "align"
                    widget: "select"
                    required: false
                    options:
                      - label: "Left"
                        value: "left"
                      - label: "Center"
                        value: "center"
                      - label: "Right"
                        value: "right"
          - label: "Full-width media"
            name: "full_width_media"
            widget: "object"
            fields: 
              - label: "Media"
                name: "media"
                widget: "image"
  - label: "People"
    label_singular: "person"
    identifier_field: name
    slug: "{{name}}"
    name: "people"
    folder: "src/about"
    create: true
    editor:
      preview: true
    fields:
      - label: "ID"
        name: "id"
        widget: "uuid"
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - lable: "Biography"
        name: "bio"
        widget: "markdown"
        required: false
      - label: "Headline"
        name: "headline"
        widget: "string"
        hint: "Quirky one-liner that displays at the top of the page"
        required: false
      - label: "Accordions"
        name: "accordions"
        widget: "object"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            default: "Studio credits"
            hint: "Title of the accordions section that displays above the accordions"
          - label: "Accordions"
            name: "accordions"
            widget: "list"
            fields:
              - label: "Preview text"
                name: "summary"
                widget: "string"
              - label: "Text content"
                name: "text"
  - label: "Pages"
    label_singular: "page"
    name: "pages"
    folder: "src/pages"
    create: true
    editor:
      preview: true
    fields:
      - label: "ID"
        name: "id"
        widget: "uuid"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description" 
        widget: "markdown"
        hint: "Displays at the top of the page"
      - label: "Collection image grid"
        name: "collection"
        widget: "select"
        required: false
        options:
          - label: "People"
            value: "people"
          - label: "Work"
            value: "work"
          - label: "Pages"
            value: "pages"
        hint: "Choose the collection whose entries you want to display as an image grid."
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - label: Title
                name: text
                widget: string
              - label: URL
                name: url
                widget: string
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - label: Title
                name: title
                widget: string
              - label: URL
                name: url
                widget: string
              - label: Description
                name: desc
                widget: string
      - label: "Global"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - label: Site title, 
            name: site_title, 
            widget: string 
          - label: "Site logo"
            name: "logo"
            widget: "image"
            default: "/static/img/winterstellar-logo.png"
      - label: "Footer"
        name: "footer"
        file: "src/_data/footer.yaml"
        fields:
          - label: "Social links"
            name: social_links
            widget: list
            fields:
              - label: 'URL'
                name: 'url'
                widget: 'list'
                hint: "If the link you desire is a page on this site, choose one of the available collections and then one of the pages from the collection."
                types:
                  - label: "Work"
                    name: work
                    widget: object
                    fields:
                    - label: 'Page'
                      name: 'page'
                      widget: relation
                      collection: "work"
                      search_fields: ["title"]
                      value_field: "id"
                  - label: "People"
                    name: people
                    widget: object
                    fields:
                    - label: 'Page'
                      name: 'page'
                      widget: relation
                      collection: "people"
                      search_fields: ["name"]
                      value_field: "id"
                      display_fields: ["name"]
                  - label: "Pages"
                    name: pages
                    widget: object
                    fields:
                    - label: "Page"
                      name: "page"
                      widget: "relation"
                      collection: "pages"
                      search_fields: ["title"]
                      value_field: "id"
                  - label: "External"
                    name: external
                    widget: object
                    fields:
                    - label: "URL"
                      name: url
                      widget: "string"
                      default: "https://www.example.com"
                      pattern: 
                        - '^(https?:\/\/|\/)\w+\.[^\s]+$|^\/[^\s]*$'
                        - "Text must be a valid URL."
              - label: Icon
                name: icon
                widget: image